---
driver:
  name: opennebula
  opennebula_endpoint: 'http://192.168.1.105:2633/RPC2'
  oneauth_file: ./oneauth
  template_name: megam
  vm_hostname: balaji
  username: megam
  public_key_path: /home/balaji/balaji.pub

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
     -recipe[owncloud::default]

